### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tavvvvvvvvvvvvvv** [Rezy774/RBX2016#1]
When I execute the script the top bar goes back to the 2016 one but the chat, backpack, menu, and playerlist are all gone.

![image](https://github.com/Rezy774/RBX2016/assets/138950887/99ef95f0-2f23-4660-b881-cd223257174f)

**Comment by tavvvvvvvvvvvvvv** [comment]
can you fix it now please

**Comment by Rezy774** [comment]
It works on some games and some days like on water park it works for me

**Comment by tavvvvvvvvvvvvvv** [comment]
it doesnt work in any of the games i tried
