### ISSUE TITLE
DOESNT WORK ON PC

### ISSUE THREAD

**Issue by tavvvvvvvvvvvvvv** [Rezy774/RBX2016#3]
I HAVE A PC AND IT DOESNT WORK
![image](https://github.com/Rezy774/RBX2016/assets/138950887/69fc378e-0ec8-434e-8a97-90a3cb9f15c6)

![image](https://github.com/Rezy774/RBX2016/assets/138950887/06c7b3ce-1c68-408d-ab21-f0674750bd9e)

**Comment by Rezy774** [comment]
bro i fixed it it works with me

**Comment by Rezy774** [comment]
i use KRNL

**Comment by Rezy774** [comment]
![Screenshot 2023-08-08 133347](https://github.com/Rezy774/RBX2016/assets/128003302/53ed88a1-ed8e-4911-b28c-b554d06ee56c)
see

**Comment by tavvvvvvvvvvvvvv** [comment]
make it work for electron

**Comment by Rezy774** [comment]
it works on some executors and some ones dont work so it is fixed js use codex for ios it has a key tho
